version: "3.7"

services:
    webcrawler:
        container_name: web-scraper
        restart: unless-stopped
        build:
            context: deploy/
            dockerfile: Dockerfile
        ports:
            - 5000:5000
        volumes:
            - ~/.aws:/root/.aws:ro
        env_file:
            - ../.env

    redis:
        container_name: redis
        image: redis
        ports:
            - 6379:6379
        volumes:
            - "./data/redis:/data"

    redis-c:
        container_name: redis-c
        image: rediscommander/redis-commander:latest
        environment:
            REDIS_HOSTS: local:redis:6379
        ports:
            - 8081:8081

